name: Python Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Check Python syntax
      run: |
        python -m py_compile pong_game.py
    
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Lint with flake8 (errors only)
      run: |
        # Check for Python syntax errors or undefined names
        flake8 pong_game.py --count --select=E9,F63,F7,F82 --show-source --statistics --max-line-length=100
      continue-on-error: false
    
    - name: Code style check (warnings)
      run: |
        # Check code style (non-blocking)
        flake8 pong_game.py --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
      continue-on-error: true
    
    - name: Verify requirements.txt exists
      run: |
        test -f requirements.txt && echo "✓ requirements.txt found" || exit 1
    
    - name: Check for common issues
      run: |
        echo "Checking for common Python issues..."
        python -c "import ast; ast.parse(open('pong_game.py').read()); print('✓ Code is syntactically valid')"
